# Generated by Django 5.0.6 on 2024-06-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, null=True, related_name='tasks_with_this_label', to='labels.label'),
        ),
    ]
