name: Linting and testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install flake8
        run: python -m pip install flake8
      - name: Linter check
        run: flake8 task_manager --exclude migrations
      - name: Install app
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
      - name: Install dependencies
        run: |
          poety shell
          make install
      - name: Run migrations
        run: make migrate
      - name: Run tests
        run: make test
      - name: Deploy on the Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"