name: Linting and testing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install flake8
        run: python -m pip install flake8
      - name: Linter check
        run: flake8 task_manager --exclude migrations
      - name: Install app
        run: |
            curl -sSL https://install.python-poetry.org | python3 -
      - name: Add Poetry to PATH
        run: echo "${HOME}/.local/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: make install
      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: make test
      - name: Deploy on the Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"