name: Linting, testing and deployment
on: push
env:
  SECRET_KEY: ${{ secrets.DJANGO_SECRET }}
  DATABASE_URL: 'sqlite:///db.sqlite3'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4.1.7
      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.x'
      - name: Install flake8
        run: python -m pip install flake8
      - name: Linter check
        run: flake8 task_manager --exclude migrations
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install
      - name: Run tests
        run: make test
      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v8.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          SECRET_KEY: ${{ secrets.DJANGO_SECRET }}
        with:
          coverageCommand: make coverage
          debug: true
      - name: Deploy on the Render
        run: curl "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"